name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.event.repository.name }}
    steps:
      - name: show REPO env variable
        run: echo ${{ env.REPO }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: set lower case owner and repository name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.client-prod
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}/client:${{ github.sha }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.server-prod
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}/server:${{ github.sha }}
